apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  namespace: monitoring
data:
  alert-rules.yml: |
    groups:
    - name: node.rules
      rules:
      - alert: NodeDown
        expr: up{job="node-exporter"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Node down ({{ $labels.instance }})"
          description: "Node {{ $labels.instance }} is down for more than 2 minutes."

      - alert: NodeHighMemoryUsage
        expr: (node_memory_Active_bytes / node_memory_MemTotal_bytes) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on node ({{ $labels.instance }})"
          description: "Memory usage > 90% on {{ $labels.instance }}."

      - alert: NodeHighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on node ({{ $labels.instance }})"
          description: "CPU usage > 90% on {{ $labels.instance }}."

      - alert: NodeDiskFull
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Disk almost full on node ({{ $labels.instance }})"
          description: "Root disk > 90% full on node {{ $labels.instance }}."

      - alert: NodeFilesystemInodesFillingUp
        expr: (node_filesystem_files_free{mountpoint="/"} / node_filesystem_files{mountpoint="/"}) < 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Inodes running out on node ({{ $labels.instance }})"
          description: "Less than 10% inodes left on root filesystem."

    - name: pod.rules
      rules:
      - alert: PodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Pod CrashLoopBackOff ({{ $labels.pod }})"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} restarted > 3 times in the last 5m."

      - alert: PodNotRunning
        expr: kube_pod_status_phase{phase=~"Failed|Unknown|Pending"} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Pod not running ({{ $labels.pod }})"
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in {{ $labels.phase }} state for >5m."

      - alert: DeploymentReplicasMismatch
        expr: kube_deployment_status_replicas_available != kube_deployment_spec_replicas
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Deployment replicas mismatch ({{ $labels.deployment }})"
          description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has unavailable replicas."

      - alert: ContainerOOMKilled
        expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container OOMKilled ({{ $labels.container }})"
          description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} was OOMKilled."
